### ISSUE TITLE
Include Maven proxy settings if available in settings.xml

### ISSUE THREAD

**Issue by gunnee** [webdriverextensions/webdriverextensions-maven-plugin#1]
com.github.webdriverextensions.Utils.downloadFile should consider proxy settings in Maven's settings.xml

**Comment by andidev** [comment]
I'll have a look at it, can you help me test it afterwards?

**Comment by andidev** [comment]
Notes to myself
http://www.mkyong.com/maven/how-to-enable-proxy-setting-in-maven/
https://github.com/github/maven-plugins/issues/32

**Comment by andidev** [comment]
It should be implemented in version 1.1.0-SNAPSHOT and ready to be release. Could you please try before I release it?

To install the 1.1.0-SNAPSHOT version please do the following:
Clone this project (or pull the changes if you already cloned it)
```bash
git clone https://github.com/webdriverextensions/webdriverextensions-maven-plugin
```

Install the maven plugin in your local .m2 repository with:
```
bash
mvn clean install
```

Now you should be able to test it by updating the version in your pom to 1.1.0-SNAPSHOT
```xml
            <plugin>
                <groupId>com.github.webdriverextensions</groupId>
                <artifactId>webdriverextensions-maven-plugin</artifactId>
                <version>1.1.0-SNAPSHOT</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>install-drivers</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

If you have multiple proxys in the settings.xml file and want to specify which one to use you can provide it in the maven configuration
```xml
            <plugin>
                <groupId>com.github.webdriverextensions</groupId>
                <artifactId>webdriverextensions-maven-plugin</artifactId>
                <version>1.1.0-SNAPSHOT</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>install-drivers</goal>
                        </goals>
                        <configuration>
                            <proxyId>yourproxyid</proxyId>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

If no proxyId is providen the first encountered active proxy will be used.

In the Maven settings.xml file you can provide non proxy hosts for a proxy
```
       <nonProxyHosts>www.google.com|*.example.com</nonProxyHosts>
```
This ignore list is however not implemented so everything will go through the proxy. Hope that is not a problem. If it is needed could try to implement this as well.

**Comment by gunnee** [comment]
Wow, nice work! I would have opened up a fork but you were faster. The RepositoryTest fails for me when installing the maven plugin because of missing proxy settings. I skipped those tests. 

However, the new version worked fine. All drivers could be downloaded.

**Comment by andidev** [comment]
Great I'll try to release it right away!
Your right about the RepositoryTest. Added a comment about the problem in the test case.
