### ISSUE TITLE
Screenshots will be overwritten when the same test fails a second time.

### ISSUE THREAD

**Issue by MarcoBeerepoot** [webdriverextensions/webdriverextensions-maven-plugin#10]
Due to the choice of naming the screenshots in this format:
TestClass.TestMethod@browser.jpg
screenshots are overwritten when the same tests fails again.
Can't you add a unique identifier like a UUID or the date/time of the failed test?

**Comment by andidev** [comment]
I guess appending a Date and time would also do it and make it more readable. I thought I implemented it so.

**Comment by MarcoBeerepoot** [comment]
I am currently using version 2.1.2 and it doesn't append the date and time. 
 Here is the code that makes up the screenshot name from the WebDriverRunner class (line 271):
if (hasTakeScreenshotOnFailureAnnotation) {
                    String fileName = className + "." + methodName;
                    screenshotRunListener = new TakeScreenshotOnFailureRunListener(log, fileName);

As you can see, no date is appended to the filename.

**Comment by MarcoBeerepoot** [comment]
Whoops... I'm sorry I placed this in the plugin repository. I should have created the issue on https://github.com/webdriverextensions/webdriverextensions.

**Comment by andidev** [comment]
No problem, this works as well. I'll have a look at tit as soon as I have time. This is probabla  a really small fix. PR's are welcome if you feel like fixing it.

**Comment by andidev** [comment]
Sorry forgot about this. I'll release this in version 2.6.2. The screenshots file name will look like this
```
ClassName.testName@Chrome-2016-04-09T23:35.png
```
