### ISSUE TITLE
Truncated zip prevents further downloads

### ISSUE THREAD

**Issue by scotty6435** [webdriverextensions/webdriverextensions-maven-plugin#11]
If the Maven task is cancelled or fails during a driver download, the truncated zip prevents further attempts to download the same file.  As the temp path is independent, the offending files must be removed manually.  Can a status be added after the file has been successfully downloaded?

**Comment by andidev** [comment]
Yes this is certainly an issue. Do you feel like looking into it and provide a PR?

**Comment by scotty6435** [comment]
Sure thing, I'll take a look in the next few days. Chances are it will mean writing a temp file for each download which includes an 'OK' message with a check for this before attempting re-download.

**Comment by andidev** [comment]
Yes that sound like the way to go.

**Comment by andidev** [comment]
Sorry for the late response. The tests have been failing for some unknown reason for the phantomjs driver and I have no idea why so I started to refactor some things. I'm working on this issue right now so you know.

**Comment by scotty6435** [comment]
No worries Anders, unfortunately I've not had a chance to look at this yet. Let me know if you need anything from me to get this sorted though and I'll try and help.

**Comment by andidev** [comment]
So I finally had some time to release this in version 2.1.0
changelog:
https://github.com/webdriverextensions/webdriverextensions-maven-plugin#210-2016-may-20
