### ISSUE TITLE
Plz add support for firefox marionette and MS Edge drivers

### ISSUE THREAD

**Issue by pumano** [webdriverextensions/webdriverextensions-maven-plugin#18]
possibility to install that type of drivers using maven plugin

**Comment by lkwg82** [comment]
you can adda custum url an a name for your driver, already tried?

**Comment by pumano** [comment]
How I can add it? Will be better to add out-of-the-box support for that browser drivers

**Comment by lkwg82** [comment]
Please at least read the f* manual ;). See https://github.com/webdriverextensions/webdriverextensions-maven-plugin#selecting-files-to-extract

**Comment by pumano** [comment]
good, thx I got it, but will be better to get it from out-of-the-box. That support will be provided?

**Comment by lkwg82** [comment]
So we will welcome your PR! Plz do small PRs. 

(Dont miss a test.)

Thx in advance!

**Comment by andidev** [comment]
So 3.0 is released and it adds support for geckodrive. edgedriver and operadriver.
