### ISSUE TITLE
Mozilla released 0.10.0 of geckodriver

### ISSUE THREAD

**Issue by pumano** [webdriverextensions/webdriverextensions-maven-plugin#23]
But update contains: "Only upgrade to this version if you are using Selenium 3 beta releases."
I'm not sure, about adding it to current repository. How guys you think about?

Also geckodriver will be only x64 for all platforms since 0.9.0

**Comment by andidev** [comment]
I'm voting for waiting until selenium 3 is released.

If one would like to use the driver one could easily add the download location manually by e.g.
```xml
<driver>
    <name>geckodriver</name>
    <platform>windows</platform>
    <bit>64</bit>
    <version>0.10.0</version>
    <url>https://github.com/mozilla/geckodriver/releases/download/v0.10.0/geckodriver-v0.10.0-win64.zip</url>
</driver>
```

I added the 0.9.0 version for x64 for all platforms. Hopefully the change in bit support does not cause any issues. I don't think it should.

**Comment by andidev** [comment]
geckodriver version 0.11.1 should now be available. Use webdriverextensions-maven-plugin version 3.1.1 to install it. Previos versions do not work.
