### ISSUE TITLE
Automatically set Selenium system properties

### ISSUE THREAD

**Issue by vmassol** [webdriverextensions/webdriverextensions-maven-plugin#26]
It would be nice if this maven plugin could set the system properties related to the driver. For example for geckodriver it's "webdriver.gecko.driver". This would make it a lot simpler for users of this plugin and prevent them from having to handle the various OS by using maven profiles in their pom.xml.

**Comment by andidev** [comment]
I have tried to implement this but did not manage to pass the system properties from the webdriverextensions maven plugin to the surefire maven plugin which runs the tests. Any ideas how to pass system properties between plugin?

**Comment by andidev** [comment]
This is what I tried doing 
https://github.com/webdriverextensions/webdriverextensions-maven-plugin/commit/5c21264933b47a9a7ed1165b263f41a27e43f299

Also see issue 
https://github.com/webdriverextensions/webdriverextensions-maven-plugin/issues/12

**Comment by vmassol** [comment]
Actually IMO the best is to implement #28 and thus set the system property in the driver factory call, e.g `ResolvingPhantomJSDriverService.createDefaultService()`. Thus all that would remain on the maven side is a dependency on an artifact.

I know it's a big change for your plugin but I feel that would really make this project interesting.

WDYT?

**Comment by vmassol** [comment]
FTR yes you're right you can't pass is to surefire.

**Comment by jschwartzenberg** [comment]
I'm running into this as well with the selenese-runner-java:
https://github.com/vmi/selenese-runner-java

I currently have this in my pom:
```
<plugin>
  <groupId>com.github.webdriverextensions</groupId>
  <artifactId>webdriverextensions-maven-plugin</artifactId>
  <version>3.1.1</version>
  <executions>
    <execution>
      <goals>
	<goal>install-drivers</goal>
      </goals>
      <phase>pre-integration-test</phase>
    </execution>
  </executions>
  <configuration>
    <installationDirectory>${buildDirectory}/drivers</installationDirectory>
    <drivers>
	<driver>
	  <name>geckodriver</name>
	</driver>
    </drivers>
  </configuration>
</plugin>
<plugin>
  <groupId>org.codehaus.mojo</groupId>
  <artifactId>exec-maven-plugin</artifactId>
  <executions>
    <execution>
    <phase>integration-test</phase>
    <goals>
      <goal>java</goal>
    </goals>
    </execution>
  </executions>
  <configuration>
    <mainClass>jp.vmi.selenium.selenese.Main</mainClass>
    <includePluginDependencies>true</includePluginDependencies>
    <arguments>
      <argument>--geckodriver</argument>
      <argument>${buildDirectory}/drivers/geckodriver-linux-64bit</argument>
      <argument>--html-result</argument>
      <argument>target/site/selenium-reports</argument>
      <argument>--xml-result</argument>
      <argument>target/failsafe-reports</argument>
      <argument>--no-exit</argument>
      <argument>${buildDirectory}/suite.html</argument>
    </arguments>
  </configuration>
  <dependencies>
    <dependency>
      <groupId>jp.vmi</groupId>
      <artifactId>selenese-runner-java</artifactId>
      <version>${selenese.runner.java.version}</version>
    </dependency>
  </dependencies>
</plugin>
</plugins>
```

But that will only work on one platform. it would already help if the output file for the driver download could be specified.

**Comment by paulwellnerbou** [comment]
A workaround could be to handle this with os specific profiles:

```xml
<profiles>
        <profile>
            <id>platform-windows</id>
            <activation>
                <os>
                    <family>windows</family>
                </os>
            </activation>
            <properties>
                <platform>windows</platform>
                <webdriver.gecko.driver.binary>geckodriver-windows-64bit.exe</webdriver.gecko.driver.binary>
            </properties>
        </profile>
        <profile>
            <id>platform-mac</id>
            <activation>
                <os>
                    <family>mac</family>
                </os>
            </activation>
            <properties>
                <platform>mac</platform>
                <webdriver.gecko.driver.binary>geckodriver-mac-64bit</webdriver.gecko.driver.binary>
            </properties>
        </profile>
        <profile>
            <id>platform-linux</id>
            <activation>
                <os>
                    <family>linux</family>
                </os>
            </activation>
            <properties>
                <platform>linux</platform>
                <webdriver.gecko.driver.binary>geckodriver-linux-64bit</webdriver.gecko.driver.binary>
            </properties>
        </profile>
    </profiles>
```

And then:
```xml
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.19.1</version>
                <configuration>
                    <includes>
                        <include>*Spec*</include>
                    </includes>
                    <systemPropertyVariables>
                        <geb.build.reportsDir>${project.build.directory}/test-reports/geb</geb.build.reportsDir>
                        <webdriver.gecko.driver>${project.basedir}/drivers/${webdriver.gecko.driver.binary}</webdriver.gecko.driver>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
```

**Comment by andidev** [comment]
The problem is that a maven plugin cannot set any property at all. So I think it is impossible to do achieve this with this plugin unless somebody proves me wrong. 
It's a good workaround though. Another solution one is to use the WebDriverRunner in the WebDriverExtensions framework which this plugin was initially made for. 


https://github.com/webdriverextensions/webdriverextensions

**Comment by sephiroth-j** [comment]
Using the System properties works only for non-forking mode of Surefire plugin, which is disabled by default. But it is possible to pass properties by [using the `userProperties` of the `MavenSession`](https://github.com/apache/maven-surefire/blob/b9b2381a3dba6574bb69bd91d45fe0edea29c779/maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java#L2883).

The feature will be disabled by default because setting properties in this way overrides any previously set properties via `systemPropertyVariables` (see [1](https://github.com/apache/maven-surefire/blob/b9b2381a3dba6574bb69bd91d45fe0edea29c779/maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/AbstractSurefireMojo.java#L1219,L1220) + [2](https://github.com/apache/maven-surefire/blob/b9b2381a3dba6574bb69bd91d45fe0edea29c779/maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/SurefireProperties.java#L148)). To enabled this feature, set `setWebdriverPath` to `true`.
