### ISSUE TITLE
Package the drivers in a maven repository

### ISSUE THREAD

**Issue by vmassol** [webdriverextensions/webdriverextensions-maven-plugin#28]
Right now this plugin will download the drivers in an installation directory. And by default it's in the current project so if you need to run this plugin on several maven modules you'll get them downloaded several times which is not nice. Ofc the user could configure the location but it would be better if it were done for him automatically. The best place when using Maven is the maven local repository. Thus it would be nice if the drivers could be deployed on Maven central (through sonatype nexus) and thus downloaded as zips by maven itself. The plugin would expand them in a temporary directory for example.

Even better would be something similar to https://github.com/qa/arquillian-phantom-driver where all you need is a maven dependency and the usage of:

`````
            DesiredCapabilities capabilities = DesiredCapabilities.phantomjs();
            driver = new PhantomJSDriver(ResolvingPhantomJSDriverService.createDefaultService(), capabilities);
`````

WDYT?

Thanks

**Comment by andidev** [comment]
This sounds like a big change and I'm not sure the maven repo should be used for binaries. 
Have you checked out the following project 
https://github.com/bonigarcia/webdrivermanager

Maybe that suits you better?

**Comment by vmassol** [comment]
Awesome, didn't know about this project, thanks for mentioning it! ;)

Maybe you guys should talk together since your 2 projects seem quite close :)

Thx again
