### ISSUE TITLE
Add support for skipping if skipTests is defined

### ISSUE THREAD

**Issue by leonard84** [webdriverextensions/webdriverextensions-maven-plugin#35]
Since this plugin is primarily used for testing, it would be a sensible default to skip the execution if `-DskipTests` is defined and not `false`. Since the handling of `skipTests` is done on its presence, it does not work to manually forward it to the configuration `<skip>${skipTests}</skip>` so explicit support is necessary. 

If someone wants to explicitly never skip the execution then they could set `<skip>false</skip>` in the configuration, which should overrule the `skipTests` parameter.

**Comment by andidev** [comment]
That is true, do you feel like making a PR? This should not be to hard to fix.

**Comment by andidev** [comment]
Released in version 3.2.0
