### ISSUE TITLE
Everyone uses the same temp-folder

### ISSUE THREAD

**Issue by thrawn-sh** [webdriverextensions/webdriverextensions-maven-plugin#37]
My students are working on their thin-clients, they are all connected to the same terminal server, with a shared temp folder. When 2 or more users run your maven plugin at the same time, the webdriverextensions-maven-plugin can not be deleted by user A if it was created by user B.

Therefore use a unique temp folder for each run.

**Comment by jsmithe** [comment]
I am having this problem when building multiple modules which use this extension.  I would take a simple REPLACE instead of of throwing a FileAlreadyExistsException but using individual directories would be nice.

**Comment by andidev** [comment]
Released in version 3.2.0
