### ISSUE TITLE
Repository URL Override

### ISSUE THREAD

**Issue by bradyrad** [webdriverextensions/webdriverextensions-maven-plugin#44]
As a user, it would be nice to override the URL of the repository or a local file path.
Currently working on a PR that demonstrates this.

**Comment by andidev** [comment]
I think actually you can do that already.

http://webdriverextensions.github.io/webdriverextensions-maven-plugin/install-drivers-mojo.html#repositoryUrl

Though maybe it should be documented in the Readme.

**Comment by bradyrad** [comment]
> I think actually you can do that already.
> 
> http://webdriverextensions.github.io/webdriverextensions-maven-plugin/install-drivers-mojo.html#repositoryUrl
> 
> Though maybe it should be documented in the Readme.

That's what we figured. I will modify the readme and add a unit test that demonstrates this workflow for a different remote path (and possibly local).
