### ISSUE TITLE
Chromium based Edgedriver exclude Driver_Notes folder

### ISSUE THREAD

**Issue by timovd** [webdriverextensions/webdriverextensions-maven-plugin#48]
When using a Chromium based Edge version (e.g. 83.0.478.50 from https://msedgedriver.azureedge.net/83.0.478.50/edgedriver_mac64.zip), there is a folder named Driver_Notes in the ZIP. When Installing the driver(s) it returns an exception; java.nio.file.NoSuchFileException: ***\Driver_Notes\credits.html
Can we ignore the Driver_Notes folder?

**Comment by tcnh** [comment]
You can, just use the following configuration for chromium edgedriver:
```
<driver>
    <name>edgedriver</name>
    <platform>windows</platform>
    <bit>64</bit>
    <version>${selenium.edgedriver.version}</version>
    <url>https://msedgedriver.azureedge.net/${selenium.edgedriver.version}/edgedriver_win64.zip</url>
    <fileMatchInside>msedgedriver.exe</fileMatchInside>
</driver>
```
Note the `fileMatchInside` parameter. This just extracts the exe, ignoring any other files
