### ISSUE TITLE
Support installing drivers when `skipTests` is true 

### ISSUE THREAD

**Issue by fhoeben** [webdriverextensions/webdriverextensions-maven-plugin#49]
In version 3.2.0 is skipped if `skipTests` is passed to the maven run, per #36 
In the original issue it was stated that this behaviour could be overridden using the configuration parameter `<skip>`. In my experience that is not what is currently implemented.
Even though I set `<skip>false</skip>` I still get the following message in my run:
```
[INFO] --- webdriverextensions-maven-plugin:3.2.0:install-drivers (default) @ hsac-fitnesse-fixtures ---
[INFO] Skipping install-drivers goal execution (skipTests)
[INFO] 
```

I want to bundle the drivers in a .zip file even though I'm currently skipping my tests.

Please add an option to allow the `skipTests` behaviour to be overridden.

**Comment by soemer** [comment]
I'm using this plugin the same way as the opener and would like to override the behaviour.

**Comment by sephiroth-j** [comment]
Version 3.3.0 has a new option `skipIgnore` to ignore `skipTests` and the other skip-options.
