### ISSUE TITLE
Plugin fails to extract driver if driver-archive contains folders

### ISSUE THREAD

**Issue by the3ver** [webdriverextensions/webdriverextensions-maven-plugin#50]
Downloading the edgedrivers currently fails im my projekt (e.g. edgedriver-windows-32bit-85.0.564.17) using version 3.2.0.
The Archive gets downloaded but can not be extracted:
```

[INFO] --- webdriverextensions-maven-plugin:3.2.0:install-drivers (default-cli) @ sednaft-engine-ml-admin ---
[INFO] Installation directory "C:\workspace\java\idea_workspace\...\drivers"
[INFO] Installing drivers from configuration
[INFO] edgedriver-windows-32bit version 85.0.564.17
[INFO]   Downloading "https://msedgedriver.azureedge.net/85.0.564.17/edgedriver_win32.zip" to "C:\WINDOWS\TEMP\webdriverextensions-maven-plugin9108440565592915644\downloads\edgedriver-windows-32bit-85.0.564.17\edgedriver_win32.zip"
[INFO]   Extracting "C:\WINDOWS\TEMP\webdriverextensions-maven-plugin9108440565592915644\downloads\edgedriver-windows-32bit-85.0.564.17\edgedriver_win32.zip" to temp folder
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.383 s
[INFO] Finished at: 2020-09-04T16:23:37+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.webdriverextensions:webdriverextensions-maven-plugin:3.2.0:install-drivers (default-cli) on project sednaft-engine-ml-admin: Failed to extract driver from "C:\WINDOWS\TEMP\webdriverextensions-maven-plugin9108440565592915644\downloads\edgedriver-windows-32bit-85.0.564.17\edgedriver_win32.zip" cause of java.nio.file.NoSuchFileException: C:\WINDOWS\TEMP\webdriverextensions-maven-plugin9108440565592915644\temp\Driver_Notes\credits.html
[ERROR]
[ERROR] driver: {
[ERROR]   "name": "edgedriver",
[ERROR]   "platform": "windows",
[ERROR]   "bit": "32",
[ERROR]   "version": "85.0.564.17",
[ERROR]   "url": "https://msedgedriver.azureedge.net/85.0.564.17/edgedriver_win32.zip"
[ERROR] }
[ERROR]
[ERROR] downloadDirectory:
[ERROR] C:\WINDOWS\TEMP\webdriverextensions-maven-plugin9108440565592915644\downloads
[ERROR] ├── edgedriver-windows-32bit-85.0.564.17\download.completed  0
[ERROR] └── edgedriver-windows-32bit-85.0.564.17\edgedriver_win32.zip     5,5 MB
[ERROR]
[ERROR] tempDirectory:
[ERROR] C:\WINDOWS\TEMP\webdriverextensions-maven-plugin9108440565592915644\temp is empty
[...]
```

The archive contains (in addition to the driver exe itself) a folder with a credits file inside ("Driver_Notes\credits.html") which seems to cause the problem. I deleted the extra folder and credits.html file, made the patched archive available under some URL and used that URL in my configuration (by `<url>` tag) : with that the error was gone.

It seems to me the plugin has a problem with driver-archives containing folders.

**Comment by the3ver** [comment]
Older versions also seem to be affected, I can reproduce the error with 3.0.2, too.

**Comment by the3ver** [comment]
As a workaround I tried filtering the archive contents using the <fileMatchInside></fileMatchInside> tag but failed so far. (<fileMatchInside>.*msedgedriver.*</fileMatchInside>)

**Comment by wildone** [comment]
Yeah same issue here, any solution for this?

**Comment by dannejosefsson** [comment]
I encountered the same issue and have some proposals on enhancements.

The issue with `<fileMatchInside>` isn't taking effect is that the [Repository.enrichDriver](https://github.com/webdriverextensions/webdriverextensions-maven-plugin/blob/8d3bf50221db05e1ee18a0439a387535dd6b2ea4/src/main/java/com/github/webdriverextensions/Repository.java#L97) isn't handling the <fileMatchInside> correctly. We should probably use the info from the pom if that is provided. It might be that there are some side effects to iron out.

I also think that the `"fileMatchInside"` property should be added for Edge (Chromium) and Opera in (https://raw.githubusercontent.com/webdriverextensions/webdriverextensions-maven-plugin-repository/master/repository-3.0.json). This would fix the issue for when one isn't specifying a particular driver version. The solution would be `fileMatchInside: "MicrosoftWebDriver.*"` for Edge and `fileMatchInside: "operadriver.*"` respectively according to my initial investigations. This also leads to the workaround I've found: if you roll your own repository.json, then you can add this line and `mvn webdriverextensions:install-drivers` will extract the correct file.

**Comment by dannejosefsson** [comment]
Pr for the repository file is created: [PR #77](https://github.com/webdriverextensions/webdriverextensions-maven-plugin-repository/pull/77).

**Comment by ikucheryavenkov** [comment]
This is fixed in my pull request. Edgedriver ZIP archive contains some file in subfolder, but it does not contain the subfolder.
